stages:
  - build

build:
  stage: build
  script:
    - cd src
    - pwd
    - dotnet pack --configuration Release
    - nuget push Locker\bin\Release\locker-secrets.0.0.3.nupkg
  tags:
    - win01
  only:
    - release
    - tags
