<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Official Locker Secret .NET SDK using the Locker SDK protocol v1.</Description>
    <PackageId>lockersm</PackageId>
    <Version>1.0.0</Version>
    <Authors>CyStack</Authors>
    <PackageTags>Locker;LockerSM;Secrets</PackageTags>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://locker.io</PackageProjectUrl>
    <RepositoryUrl>https://git.cystack.org/locker/secrets-sdk/dotnet</RepositoryUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
    <EmbeddedResource Include="locker-cli-release.json" LogicalName="Locker.locker-cli-release.json" />
    <EmbeddedResource Include="Protocol\locker-rpc-errors.v1.json"
                      LogicalName="Locker.Protocol.locker-rpc-errors.v1.json" />
    <None Update="Protocol\locker-rpc-errors.v1.json"
          Pack="true"
          PackagePath="protocol" />
  </ItemGroup>
</Project>
